/**
 * Plastic types per manufacturer (keys match MFRS / MOLD_LOOKUP strings exactly).
 */

export const PLASTIC_TYPES = {
  Axiom: [
    'Electron',
    'Electron Soft',
    'Electron Firm',
    'Neutron',
    'Neutron Soft',
    'Cosmic Neutron',
    'Proton',
    'Proton Soft',
    'Plasma',
    'Fission',
    'Eclipse 2.0',
  ],
  Clash: ['Steady', 'Hardy', 'Tone', 'Double Blend', 'Softy', 'Glow Steady'],
  DGA: ['ProLine', 'SP Line', 'D-Line', 'Flex', 'Signature Line'],
  Discmania: [
    'D-Line',
    'S-Line',
    'C-Line',
    'Glow C-Line',
    'Metal Flake C-Line',
    'Lux Vapor',
    'Lux',
    'Neo',
    'Vapor',
    'Horizon',
    'Meta',
    'Active',
    'Active Premium',
    'Exo Soft',
    'Exo Hard',
  ],
  Discraft: [
    'Pro-D',
    'X',
    'Z',
    'Z FLX',
    'Z Lite',
    'Big Z',
    'ESP',
    'ESP FLX',
    'Titanium',
    'CryZtal',
    'CryZtal FLX',
    'Jawbreaker',
    'Rubber Blend',
    'Special Blend',
    'Metallic Z',
  ],
  'Dynamic Discs': [
    'Classic',
    'Classic Blend',
    'Classic Soft',
    'Prime',
    'Prime Burst',
    'Fuzion',
    'Fuzion Burst',
    'Fuzion Orbit',
    'Lucid',
    'Lucid-X',
    'Lucid Air',
    'Moonshine',
    'Chameleon',
  ],
  'Flight Lab Discs': [],
  Gateway: [
    'Sure-Grip',
    'Super Soft',
    'Super Stupid Soft',
    'Eraser',
    'Organic',
    'Diamond',
    'Platinum',
    'Evolution',
    'Nylon',
    'RFF',
    'Hemp',
  ],
  'Infinite Discs': [
    'D-Blend',
    'I-Blend',
    'S-Blend',
    'G-Blend',
    'C-Blend',
    'Metal Flake C-Blend',
    'Glow C-Blend',
    'X-Blend',
    'Luster',
  ],
  Innova: [
    'DX',
    'Pro',
    'R-Pro',
    'KC Pro',
    'XT',
    'Star',
    'GStar',
    'Star Lite',
    'Champion',
    'Metal Flake Champion',
    'Blizzard Champion',
    'Halo Star',
    'Luster Champion',
    'Color Glow Champion',
    'Nexus',
    'Echo Star',
  ],
  Kastaplast: ['K1', 'K1 Soft', 'K1 Glow', 'K2', 'K3', 'K3 Hard'],
  'Latitude 64': [
    'Retro',
    'Retro Burst',
    'Eco Gold',
    'Gold',
    'Gold-X',
    'Gold Orbit',
    'Opto',
    'Opto-X',
    'Opto Air',
    'Opto Ice',
    'Royal Grand',
    'Royal Sense',
    'Royal Glory',
    'Zero Soft',
    'Zero Medium',
    'Zero Hard',
  ],
  'Lone Star': ['V1', 'V2', 'Alpha', 'Bravo', 'Delta 1', 'Delta 2', 'Lima', 'Founders'],
  Millennium: ['Standard', 'Sirius', 'Quantum', 'Lunar', 'ET'],
  Mint: ['Eternal', 'Firm Eternal', 'Sublime', 'Apex', 'Nocturnal'],
  MVP: [
    'Electron',
    'Electron Soft',
    'Electron Firm',
    'Neutron',
    'Neutron Soft',
    'Cosmic Neutron',
    'Proton',
    'Proton Soft',
    'Plasma',
    'Fission',
    'Eclipse 2.0',
  ],
  Prodigy: ['200', '300', '300 Soft', '350G', '400', '400G', '400G Spectrum', '500', '750', '750G'],
  RPM: ['Strata', 'Atomic', 'Cosmic', 'Magma', 'Glow', 'Evolution'],
  Streamline: [
    'Electron',
    'Electron Soft',
    'Electron Firm',
    'Neutron',
    'Neutron Soft',
    'Cosmic Neutron',
    'Proton',
    'Plasma',
    'Fission',
    'Eclipse 2.0',
  ],
  TSA: ['Nerve', 'Muse', 'Aura', 'Ethos', 'Ethereal', 'Nebula Ethereal'],
  Westside: [
    'Origio',
    'Origio Burst',
    'Tournament',
    'Tournament Burst',
    'Tournament Orbit',
    'VIP',
    'VIP-X',
    'VIP Air',
    'Moonshine',
    'BT Soft',
    'BT Medium',
    'BT Hard',
  ],
};

/**
 * @param {string | undefined | null} manufacturer
 * @returns {string[]}
 */
export function getPlasticsForManufacturer(manufacturer) {
  if (!manufacturer) return [];
  const list = PLASTIC_TYPES[manufacturer];
  return Array.isArray(list) ? list : [];
}
